# Generated by Django 2.2.7 on 2019-12-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apparel_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image_id', models.CharField(max_length=20)),
                ('old_name', models.CharField(max_length=50)),
                ('cluster_id', models.PositiveSmallIntegerField()),
                ('latent_code1', models.FloatField()),
                ('latent_code2', models.FloatField()),
                ('latent_code3', models.FloatField()),
                ('latent_code4', models.FloatField()),
                ('latent_code5', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cluster_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.PositiveSmallIntegerField()),
                ('latent_code1', models.FloatField()),
                ('latent_code2', models.FloatField()),
                ('latent_code3', models.FloatField()),
                ('latent_code4', models.FloatField()),
                ('latent_code5', models.FloatField()),
            ],
        ),
    ]
